### ISSUE TITLE
Avatar Component

### ISSUE THREAD

**Issue by kscherling** [revelation/ember-cli-revelation-ui#50]
- Accepts avatar url, screen name, role, segment, size
- three sizes lg, md, sm
- if participant outlines with segment color

**Comment by zulaica** [comment]
What should the three sizes be set to? 32px for md?

**Comment by zulaica** [comment]
@kscherling: Opted for 16, 32, and 48 in initial branch. A couple questions:

What will we be using the screen name for? I guess my question is if that needs to be explicitly passed into the component or if it's something that can be handled automagically elsewhere.

Is Participant the only role we care about to handle border color?

WIP branch is over here: https://github.com/revelation/ember-cli-revelation-ui/commit/76d8550dd9b728121c9f7de7aaf9340d2e7affcd

**Comment by kscherling** [comment]
I believe we use 24, 32, 42.  Only participants will need the border.  We'll also need to set border color bases on the segment.  Screen name is passed for hover tip and aria labeling.  It may make more sense to just pass the whole user object in and since we are likely rebuilding these Apis it might be a good time to sit down and look at how me want to organize those objects.

On Fri, Sep 4, 2015 at 4:00 PM, David Zulaica <notifications@github.com> wrote:

@kscherling<https://github.com/kscherling>: Opted for 16, 32, and 48 in initial branch. A couple questions:

What will we be using the screen name for? I guess my question is if that needs to be explicitly passed into the component or if it's something that can be handled automagically elsewhere.

Is Participant the only role we care about to handle border color?

WIP branch is over here: 76d8550<https://github.com/revelation/ember-cli-revelation-ui/commit/76d8550dd9b728121c9f7de7aaf9340d2e7affcd>

—
Reply to this email directly or view it on GitHub<https://github.com/revelation/ember-cli-revelation-ui/issues/50#issuecomment-137874969>.

Kyle Scherling


Phone:   +1 503.734.8101

FocusVision |  www.focusvision.com<http://www.focusvision.com>
Find us on:  Twitter<https://twitter.com/FocusVisionInfo> | Facebook<https://www.facebook.com/FocusVisionWW> | LinkedIn<https://www.linkedin.com/company/focusvision?trk=company_logo> | GooglePlus<https://plus.google.com/+Focusvision/posts>

**Comment by zulaica** [comment]
I think it makes most sense to pass the whole user object. That would give us both the screen name and the role.
